@startuml kizzy


(*)-->"input email"
-->"send code to email"

if "recieve code" then
    -->[yes]"input code"
    if "verify" then 
      -->[yes]"reset successfully"
      -->(*)
    else
      -->[no]"input email"
    endif
else
    --->[no]"send code to email"
endif
@enduml