@startuml login

actor User as user
participant Web as web
participant UserService as us

activate web

user -> web: click "login"
user -> web: click "Forget Password"
web -> user: showForgetpasswordForm()
user -> web : input email
user -> web : click "send code"
web -> us : requestCode()
us -> user : sendCode()
user -> web : input code and  new password
user -> web : click "Reset Password"

activate us
    web -> us : requestResetPassword()
    us -> us: resetPassword()
    alt if the code is wrong
        us -> web :returnResetError()
        web -> user : displayErrorMessage()
    else if the code is correct 
      
        us -> web :returnResetSuccess()
        web -> user : displaySuccessMessage()
        web -> user: redirect()
    end
    deactivate us

deactivate web

@enduml